  [env]
TERM = "xterm-256color"

[general]
live_config_reload = true

[window]
decorations = "None"
opacity = 0.95
startup_mode = "Maximized"
dynamic_title = true
dynamic_padding = true
padding = { x = 0, y = 0 }
blur = false

[font]
normal = {family = "Iosevka Nerd Font", style = "Medium"}
size = 15

[colors]
[colors.primary]
background = "#020202"

[selection]
save_to_clipboard = false

[mouse]
hide_when_typing = true
