[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

[window]
decorations = "Full"
# opacity = 0.9
startup_mode = "Maximized"
dynamic_title = true
dynamic_padding = true
padding = { x = 0, y = 0 }
blur = true

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 15

[colors]
[colors.primary]
background = "#000000"

[selection]
save_to_clipboard = false

[mouse]
hide_when_typing = true
