# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
$directory\
$hostname\
$character\
"""

right_format = """
$vcsh\
$git_branch\
$git_status\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[λ](yellow)"
error_symbol = "[λ](red)"
vimcmd_symbol = "[λ](green)"

[directory]
style = "white"

[git_branch]
format = "[$branch]($style)"
style = "white"
[git_status]
format = "([$modified]($style))"
style = "bright-black"
modified = "*"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
format = ' ([↑ $added]($added_style)) ([↓ $deleted]($deleted_style))'
added_style = 'dimmed green'    # Removed "italic"
deleted_style = 'dimmed red'    # Removed "italic"
ignore_submodules = true
disabled = false
